export const FETCH_SHARE_DATA = 'FETCH_SHARE_DATA';
export const RECEIVE_SHARE_DATA = 'RECEIVE_SHARE_DATA';
export const FETCH_NEWS_DATA = 'FETCH_NEWS_DATA';
export const RECEIVE_NEWS_DATA = 'RECEIVE_NEWS_DATA';