export default {
    shareData: [],
    newsData: [],
    shareList: [
        { "id": "AAPL", "name": "Apple Inc.", "icon": "apple-logo_amrzzo.png" }, 
        { "id": "ADI", "name": "Analog Devices, Inc.", "icon": "ad.png" }, 
        { "id": "ALGN", "name": "Align Technology, Inc.", "icon": "align.png" }, 
        { "id": "ASML", "name": "ASML Holding NV", "icon": "asml.png" }, 
        { "id": "BIDU", "name": "Baidu Inc", "icon": "baidu.png" }, 
        { "id": "BMRN", "name": "BioMarin Pharmaceutical Inc.", "icon": "biomarin.png" }, 
        { "id": "CERN", "name": "Cerner Corporation", "icon": "cerner.png" }, 
        { "id": "CMCSA", "name": "Comcast Corporation", "icon": "comcast.png" }, 
        { "id": "CSX", "name": "CSX Corporation", "icon": "csx.png" }, 
        { "id": "CTSH", "name": "Cognizant Technology Solutions", "icon": "cognizant.png" }, 
        { "id": "EA", "name": "Electronic Arts Inc.", "icon": "ea.png" }, 
        { "id": "FOX", "name": "Fox Corp Class B", "icon": "fox.png" }, 
        { "id": "HSIC", "name": "Henry Schein, Inc.", "icon": "henry.png" }, 
        { "id": "INCY", "name": "Incyte Corporation", "icon": "incyte.png" }, 
        { "id": "KHC", "name": "Kraft Heinz Co", "icon": "kraft.png" }, 
        { "id": "LBTYK", "name": "Liberty Global PLC Class C", "icon": "liberty.png" }, 
        { "id": "M", "name": "Macy's Inc", "icon": "macys.png" }, 
        { "id": "MDLZ", "name": "Mondelez International", "icon": "modelez.png" }, 
        { "id": "MSFT", "name": "Microsoft Corporation", "icon": "microsoft.png" }, 
        { "id": "NTES", "name": "NetEase Inc", "icon": "netease.png" }, 
        { "id": "ORLY", "name": "O'Reilly Automotive Inc", "icon": "oreilly.png" }, 
        { "id": "PEP", "name": "PepsiCo, Inc.", "icon": "pepsi.png" }, 
        { "id": "REGN", "name": "Regeneron Pharmaceuticals Inc", "icon": "regeneron.png" }, 
        { "id": "SIRI", "name": "Sirius XM Holdings Inc", "icon": "sirius.png" }, 
        { "id": "SYMC", "name": "Symantec Corporation", "icon": "symantec.png" }, 
        { "id": "ULTA", "name": "Ulta Beauty Inc", "icon": "ulta.png" }, 
        { "id": "VRTX", "name": "Vertex Pharmaceuticals Inc.", "icon": "vertex.png" }, 
        { "id": "WDC", "name": "Western Digital Corp", "icon": "western.png" }, 
        { "id": "XEL", "name": "Xcel Energy Inc", "icon": "xcel.png" }
    ]
};